In [1]:
import numpy as np

## 1D Array

In [15]:
list1=[1,2,3,4]
one_D=np.array(list1)
print(one_D)

[1 2 3 4]


In [17]:
print(type(one_D))

<class 'numpy.ndarray'>


In [18]:
one_D.ndim

1

## 2D Array

In [19]:
list2=list(range(1,11))
two_D=np.array([list2])
print(two_D)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [20]:
print(type(two_D))

<class 'numpy.ndarray'>


In [21]:
print(two_D.ndim)

2


## 3D Array

In [23]:
list3=[[1,2,3],[4,5,6],[7,8,9]]
three_D=np.array([list3])
print(three_D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [24]:
print(three_D.ndim)

3


In [29]:
def info(x):
    print("The type of element is:-",type(x))
    print("The dimension of Array is:-",x.ndim)

In [30]:
info(three_D)

The type of element is:- <class 'numpy.ndarray'>
The dimension of Array is:- 3


In [31]:
list11=[1,1.5,"Swapnil"]
list11

[1, 1.5, 'Swapnil']

In [32]:
arr=list(range(1,11))
numpy=np.array(arr)

In [33]:
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
hetero_numpy=np.array(list11)
hetero_numpy

array(['1', '1.5', 'Swapnil'], dtype='<U32')

In [39]:
hetero_numpy.dtype

dtype('<U32')

In [40]:
array1=np.array([5,10,15,20,25])
print(array1)

[ 5 10 15 20 25]


In [41]:
array1/5

array([1., 2., 3., 4., 5.])

In [42]:
list12=[5,10,15,20,25]
print(list12)

[5, 10, 15, 20, 25]


In [43]:
list12/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [48]:
b=[[1,2,3],[4,5,6],[7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
B=np.array(b)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
New_B=B.reshape(9)

In [51]:
New_B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
c=[[1,2,3,4],[4,5,6,7],[7,8,9,10]]
c

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]

In [54]:
C=np.array(c)
C

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [55]:
New_C=C.reshape(4,-1)
New_C

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [57]:
New_C=C.reshape(4,3)
New_C

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [59]:
a=np.array(range(1,5))
a

array([1, 2, 3, 4])

In [60]:
print(a[-1])
print(a[3])

4
4


In [61]:
print(a[1])
print(a[-3])

2
2


In [62]:
d=[[1,2],[3,4]]
D=np.array(d)
D

array([[1, 2],
       [3, 4]])

In [64]:
print(D[0,0])

1


In [65]:
print(D[-2,-2])

1


In [66]:
e=[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
e

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [67]:
E=np.array(e)
E

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
print(E[0][0][0])

1


In [ ]:
print(E[])