In [1]:
import numpy as np

## 1D Array

In [15]:
list1=[1,2,3,4]
one_D=np.array(list1)
print(one_D)

[1 2 3 4]


In [17]:
print(type(one_D))

<class 'numpy.ndarray'>


In [18]:
one_D.ndim

1

## 2D Array

In [19]:
list2=list(range(1,11))
two_D=np.array([list2])
print(two_D)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [20]:
print(type(two_D))

<class 'numpy.ndarray'>


In [21]:
print(two_D.ndim)

2


## 3D Array

In [23]:
list3=[[1,2,3],[4,5,6],[7,8,9]]
three_D=np.array([list3])
print(three_D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [24]:
print(three_D.ndim)

3


In [29]:
def info(x):
    print("The type of element is:-",type(x))
    print("The dimension of Array is:-",x.ndim)

In [30]:
info(three_D)

The type of element is:- <class 'numpy.ndarray'>
The dimension of Array is:- 3
