In [1]:
import numpy as np

## 1D Array

In [15]:
list1=[1,2,3,4]
one_D=np.array(list1)
print(one_D)

[1 2 3 4]


In [17]:
print(type(one_D))

<class 'numpy.ndarray'>


In [18]:
one_D.ndim

1

## 2D Array

In [19]:
list2=list(range(1,11))
two_D=np.array([list2])
print(two_D)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [20]:
print(type(two_D))

<class 'numpy.ndarray'>


In [21]:
print(two_D.ndim)

2


## 3D Array

In [23]:
list3=[[1,2,3],[4,5,6],[7,8,9]]
three_D=np.array([list3])
print(three_D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [24]:
print(three_D.ndim)

3


In [29]:
def info(x):
    print("The type of element is:-",type(x))
    print("The dimension of Array is:-",x.ndim)

In [30]:
info(three_D)

The type of element is:- <class 'numpy.ndarray'>
The dimension of Array is:- 3


In [31]:
list11=[1,1.5,"Swapnil"]
list11

[1, 1.5, 'Swapnil']

In [32]:
arr=list(range(1,11))
numpy=np.array(arr)

In [33]:
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
hetero_numpy=np.array(list11)
hetero_numpy

array(['1', '1.5', 'Swapnil'], dtype='<U32')

In [39]:
hetero_numpy.dtype

dtype('<U32')

In [40]:
array1=np.array([5,10,15,20,25])
print(array1)

[ 5 10 15 20 25]


In [41]:
array1/5

array([1., 2., 3., 4., 5.])

In [42]:
list12=[5,10,15,20,25]
print(list12)

[5, 10, 15, 20, 25]


In [43]:
list12/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [48]:
b=[[1,2,3],[4,5,6],[7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
B=np.array(b)
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
New_B=B.reshape(9)

In [51]:
New_B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
c=[[1,2,3,4],[4,5,6,7],[7,8,9,10]]
c

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]

In [54]:
C=np.array(c)
C

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [55]:
New_C=C.reshape(4,-1)
New_C

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [57]:
New_C=C.reshape(4,3)
New_C

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [59]:
a=np.array(range(1,5))
a

array([1, 2, 3, 4])

In [60]:
print(a[-1])
print(a[3])

4
4


In [61]:
print(a[1])
print(a[-3])

2
2


In [62]:
d=[[1,2],[3,4]]
D=np.array(d)
D

array([[1, 2],
       [3, 4]])

In [64]:
print(D[0,0])

1


In [65]:
print(D[-2,-2])

1


In [66]:
e=[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
e

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [67]:
E=np.array(e)
E

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [68]:
print(E[0][0][0])

1


In [70]:
print(E[0][2][0])

7


In [1]:
import numpy as np

## Slicing Operation

In [4]:
a=[1,4,7,11,6,3]
A=np.array(a)
A

array([ 1,  4,  7, 11,  6,  3])

In [5]:
# let's get element [4,7,11] from the array A
print(A[1:4])

[ 4  7 11]


In [6]:
# let's get element [1,4,7] from the array A
print(A[0:3])

[1 4 7]


In [7]:
# let's get first 3 elements
A[:3]

array([1, 4, 7])

In [8]:
#lets get all element from 2nd index to all
A[2:]

array([ 7, 11,  6,  3])

In [9]:
# let's print element with stepsize of 2
A[::2]

array([1, 7, 6])

In [10]:
# get all elements
A[::]

array([ 1,  4,  7, 11,  6,  3])

In [11]:
b=[[4,7,11],[6,13,9],[2,12,100]]
B=np.array(b)
B

array([[  4,   7,  11],
       [  6,  13,   9],
       [  2,  12, 100]])

In [12]:
#let's get element 9 and 100
B[1:3,2:3]

array([[  9],
       [100]])

In [16]:
#lets get sub matrix [[6,13],[2,12]
B[1:,0:2]

array([[ 6, 13],
       [ 2, 12]])

## View and Copy

In [25]:
arr1=np.array([10,20,30,40])
arr1

array([10, 20, 30, 40])

In [26]:
arr2=arr1.view()
arr2

array([10, 20, 30, 40])

In [27]:
arr2[1]=1000

In [28]:
arr2

array([  10, 1000,   30,   40])

In [29]:
arr1

array([  10, 1000,   30,   40])

In [30]:
# we clearly see that changes made in array2 got reflected in array1

In [31]:
arr3=np.array([10,20,30,40])
arr3

array([10, 20, 30, 40])

In [33]:
arr4=arr3.copy()
arr4

array([10, 20, 30, 40])

In [34]:
arr4[1]=1000

In [35]:
arr4

array([  10, 1000,   30,   40])

In [36]:
arr3

array([10, 20, 30, 40])

In [ ]:
# Here we clearly see that changes made in array3 not reflected in array4